App\Entity\Comment:
    type: entity
    table: comment
    indexes:
        IDX_53AD8F83F675F31B:
            columns:
                - author_id
        IDX_53AD8F834B89032C:
            columns:
                - post_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        content:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        publishedAt:
            type: datetime
            nullable: false
            column: published_at

    manyToOne:
        author:
            targetEntity: User
            nullable: false
            options:
                unsigned: false
            column: author_id
        post:
            targetEntity: LeaseRequest
            inversedBy: comments
            cascade: [ persist, remove ]
            joinColumn:
                name: post_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
