App\Entity\LeaseRequest:
    type: entity
    table: lease_request
    repositoryClass: App\Repository\LeaseRequestRepository

    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        summary:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        publishedAt:
            type: datetime
            nullable: false
            column: published_at
        start_date:
            type: datetime
            nullable: true
            column: start_date
        end_date:
            type: datetime
            nullable: true
            column: end_date
        association_type:
            type: string
            nullable: false
            column: association_type
        price:
            type: float
            nullable: true
            column: price
        status:
            type: string
            nullable: true
            column: status
        num_attendants:
            type: integer
            nullable: false
            column: num_attendants
        association:
            type: string
            nullable: false
            column: association
        contract:
            type: string
            nullable: true
            column: contract
        contract_signed:
            type: string
            nullable: true
            column: contract_signed
        read:
            type: boolean
            nullable: true
            column: read
        paid:
            type: float
            nullable: true
            column: paid

    manyToOne:
        author:
            targetEntity: User
            inversedBy: leases
            cascade: [ persist, remove ]
            joinColumn:
                name: author_id
                referencedColumnName: id

    oneToMany:
        comments:
            targetEntity: App\Entity\Comment
            mappedBy: post
            orphanRemoval: true
            cascade: [ persist ]
            orderBy: {'publishedAt': 'DESC'}

    manyToMany:
        tags:
            targetEntity: App\Entity\Tag
            joinTable:
                name: post_tag
                joinColumns:
                    user:
                        referencedColumnName: id

    lifecycleCallbacks: {  }
