App\Entity\Post:
    type: entity
    table: post
    indexes:
        IDX_58A92E65F675F31B:
            columns:
                - author_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        authorId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: author_id
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        summary:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        content:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        publishedAt:
            type: datetime
            nullable: false
            column: published_at
    lifecycleCallbacks: {  }
