App\Entity\Post:
    type: entity
    table: post

    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        slug:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        summary:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        content:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        publishedAt:
            type: datetime
            nullable: false
            column: published_at

    manyToOne:
        author:
            targetEntity: User
            joinColumn:
                name: author_id
                referencedColumnName: id

    OneToMany:
        comments:
            targetEntity: App\Entity\Comment
            mappedBy: post
            orphanRemoval: true
            cascade:
                -persist

    manyToMany:
        tags:
            targetEntity: App\Entity\Tag
            joinTable:
                name: post_tag
                joinColumns:
                    user:
                        referencedColumnName: id

    lifecycleCallbacks: {  }
